spring.application.name=reporteCrediticio

# Configuracion de conexion a MongoDb
spring.data.mongodb.uri=mongodb://localhost:27017/Buro
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Buro

# Configuracion de conexi0n a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mybdpostgres
spring.datasource.username=roque
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernat\e.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
